# SPDX-FileCopyrightText: 2026 Scitrera LLC
# SPDX-FileCopyrightText: 2026 Fox Engine Ltd
# SPDX-License-Identifier: AGPL-3.0-only

target-version = "py312"
line-length = 100

[lint]
select = ["E4", "E7", "E9", "F", "B"]
