# SPDX-FileCopyrightText: 2026 Scitrera LLC
# SPDX-FileCopyrightText: 2026 Fox Engine Ltd
# SPDX-License-Identifier: AGPL-3.0-only

"""Engine-neutral ColdSnap contracts and artifact transports."""

from .hydration import (
    CaptureDigest,
    CaptureExtent,
    CaptureMetrics,
    CaptureResult,
    HydrationError,
    HydrationExtent,
    HydrationMetrics,
    NativeHydrator,
    capture_from_env,
    hydrator_from_env,
)

from .memory import (
    CUDA_GRAPH,
    EXTERNAL,
    KV_CACHE,
    STANDARD_REGIONS,
    WEIGHTS,
    WORKSPACE,
    HostStage,
    CheckpointMemoryProvider,
    MemoryCheckpointAction,
    MemoryCheckpointPlan,
    MemoryCapabilityError,
    MemoryLayoutDescriptor,
    MemoryLayoutKind,
    MemoryRegion,
    MemoryResidencyStats,
    MemoryTransportAction,
    NoopRegionController,
    PreservationPolicy,
    ProviderCapabilities,
    RegionController,
    SnapshotMemoryProvider,
    agree_checkpoint_plans,
    require_checkpoint_plan,
    resolve_regions,
)
from .validation import (
    PayloadValidationError,
    file_sha256,
    publish_validation_record,
    validate_payload,
    validation_record_path,
    verify_validation_record,
)
from .topology import execution_graph, global_rank, worker_id, world_group

__all__ = [
    "CUDA_GRAPH",
    "EXTERNAL",
    "KV_CACHE",
    "STANDARD_REGIONS",
    "WEIGHTS",
    "WORKSPACE",
    "CaptureDigest",
    "CaptureExtent",
    "CaptureMetrics",
    "CaptureResult",
    "HydrationError",
    "HydrationExtent",
    "HydrationMetrics",
    "NativeHydrator",
    "HostStage",
    "CheckpointMemoryProvider",
    "MemoryCheckpointAction",
    "MemoryCheckpointPlan",
    "MemoryCapabilityError",
    "MemoryLayoutDescriptor",
    "MemoryLayoutKind",
    "MemoryRegion",
    "MemoryResidencyStats",
    "MemoryTransportAction",
    "NoopRegionController",
    "PreservationPolicy",
    "ProviderCapabilities",
    "RegionController",
    "SnapshotMemoryProvider",
    "agree_checkpoint_plans",
    "capture_from_env",
    "hydrator_from_env",
    "require_checkpoint_plan",
    "resolve_regions",
    "file_sha256",
    "PayloadValidationError",
    "publish_validation_record",
    "validate_payload",
    "validation_record_path",
    "verify_validation_record",
    "execution_graph",
    "global_rank",
    "worker_id",
    "world_group",
]
